import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/app/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="max-w-[1580px] mx-auto">
        <Nav></Nav>
        {children}
      </div>
      </body>
    </html>
  );
}
